# Generated by Django 2.0 on 2018-03-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buydetail',
            name='parking',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rentdetail',
            name='parking',
            field=models.CharField(max_length=50),
        ),
    ]
