# Generated by Django 2.0 on 2018-03-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_portal', '0002_auto_20180314_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buydetail',
            name='buy',
        ),
        migrations.RemoveField(
            model_name='rentdetail',
            name='rent',
        ),
        migrations.DeleteModel(
            name='Sell',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='flat_image',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='flat_type',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='flat_image',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='flat_type',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='price',
        ),
        migrations.AddField(
            model_name='buy',
            name='balconies',
            field=models.CharField(choices=[('1', '1 Balcony'), ('2', '2 Balconies'), ('3', '3 Balconies'), ('4', '4 Balconies')], default='Not Available', max_length=5),
        ),
        migrations.AddField(
            model_name='buy',
            name='bathroom',
            field=models.CharField(choices=[('1', '1 Bathroom'), ('2', '2 Bathroom'), ('3', '3 Bathroom'), ('4', '4 Bathroom')], default='1 Bathroom', max_length=5),
        ),
        migrations.AddField(
            model_name='buy',
            name='bedroom',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='buy',
            name='city',
            field=models.CharField(choices=[('DL', 'Delhi'), ('MB', 'Mumbai'), ('KK', 'Kolkata'), ('CN', 'Channai'), ('ND', 'Noida'), ('GD', 'Gurugram'), ('DN', 'Dehradun'), ('BL', 'Bangluru'), ('PN', 'Pune')], default='Select City', max_length=5),
        ),
        migrations.AddField(
            model_name='buy',
            name='facing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buy',
            name='furnished_state',
            field=models.CharField(choices=[('NF', 'Not Furnished'), ('SF', 'Semi-Furnished'), ('FF', 'Full Furnished')], default='Not Furnished', max_length=5),
        ),
        migrations.AddField(
            model_name='buy',
            name='image1',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='buy',
            name='image2',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='buy',
            name='image3',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='buy',
            name='image4',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='buy',
            name='parking',
            field=models.CharField(choices=[('AVC', 'Available, Closed'), ('AVO', 'Available, Open'), ('NAV', 'Not Available')], default='Not Available', max_length=5),
        ),
        migrations.AddField(
            model_name='buy',
            name='property_for',
            field=models.CharField(choices=[('RES', 'Residential'), ('COM', 'Commercial')], default='Select Property for', max_length=5),
        ),
        migrations.AddField(
            model_name='buy',
            name='property_type',
            field=models.CharField(choices=[('1B', '1 BHK'), ('2B', '2 BHK'), ('3B', '3 BHK'), ('4B', '4 BHK'), ('5B', '5 BHK'), ('6B', '6 BHK')], default='Select property_type', max_length=5),
        ),
        migrations.AddField(
            model_name='buy',
            name='user_info',
            field=models.CharField(choices=[('OWN', 'Owner'), ('AGN', 'Agent')], default='Select User', max_length=5),
        ),
        migrations.AddField(
            model_name='rent',
            name='balconies',
            field=models.CharField(choices=[('1', '1 Balcony'), ('2', '2 Balconies'), ('3', '3 Balconies'), ('4', '4 Balconies')], default='Not Available', max_length=5),
        ),
        migrations.AddField(
            model_name='rent',
            name='bathroom',
            field=models.CharField(choices=[('1', '1 Bathroom'), ('2', '2 Bathroom'), ('3', '3 Bathroom'), ('4', '4 Bathroom')], default='1 Bathroom', max_length=5),
        ),
        migrations.AddField(
            model_name='rent',
            name='bedroom',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='city',
            field=models.CharField(choices=[('DL', 'Delhi'), ('MB', 'Mumbai'), ('KK', 'Kolkata'), ('CN', 'Channai'), ('ND', 'Noida'), ('GD', 'Gurugram'), ('DN', 'Dehradun'), ('BL', 'Bangluru'), ('PN', 'Pune')], default='Select City', max_length=5),
        ),
        migrations.AddField(
            model_name='rent',
            name='extra_wases',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='facing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='furnished_state',
            field=models.CharField(choices=[('NF', 'Not Furnished'), ('SF', 'Semi-Furnished'), ('FF', 'Full Furnished')], default='Full Furnished', max_length=5),
        ),
        migrations.AddField(
            model_name='rent',
            name='image1',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='rent',
            name='image2',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='rent',
            name='image3',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='rent',
            name='image4',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='rent',
            name='monthly_charges',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='parking',
            field=models.CharField(choices=[('AVC', 'Available, Closed'), ('AVO', 'Available, Open'), ('NAV', 'Not Available')], default='Not Available', max_length=5),
        ),
        migrations.AddField(
            model_name='rent',
            name='property_for',
            field=models.CharField(choices=[('RES', 'Residential'), ('COM', 'Commercial')], default='Select Property for', max_length=5),
        ),
        migrations.AddField(
            model_name='rent',
            name='property_type',
            field=models.CharField(choices=[('1B', '1 BHK'), ('2B', '2 BHK'), ('3B', '3 BHK'), ('4B', '4 BHK'), ('5B', '5 BHK'), ('6B', '6 BHK')], default='Select property_type', max_length=5),
        ),
        migrations.AddField(
            model_name='rent',
            name='user_info',
            field=models.CharField(choices=[('OWN', 'Owner'), ('AGN', 'Agent')], default='Select User', max_length=5),
        ),
        migrations.AddField(
            model_name='rent',
            name='w_e_charges',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.DeleteModel(
            name='BuyDetail',
        ),
        migrations.DeleteModel(
            name='RentDetail',
        ),
    ]
