# Generated by Django 2.0 on 2018-03-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_portal', '0003_auto_20180318_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='address',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='rent',
            name='address',
            field=models.TextField(max_length=1000),
        ),
    ]
