# Generated by Django 2.0 on 2018-03-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_portal', '0005_auto_20180319_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
