# Generated by Django 2.0 on 2018-03-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_portal', '0007_auto_20180319_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='city',
            field=models.CharField(choices=[('', 'Select City'), ('Dehli', 'Delhi'), ('Mumbai', 'Mumbai'), ('Kolkata', 'Kolkata'), ('Channai', 'Channai'), ('Noida', 'Noida'), ('Gurugram', 'Gurugram'), ('Dehradun', 'Dehradun'), ('Bangluru', 'Bangluru'), ('Pune', 'Pune')], max_length=5),
        ),
        migrations.AlterField(
            model_name='buy',
            name='parking',
            field=models.CharField(choices=[('', 'Select Parking'), ('Available, Closed', 'Available, Closed'), ('Available, Open', 'Available, Open'), ('Not Available', 'Not Available')], max_length=5),
        ),
        migrations.AlterField(
            model_name='buy',
            name='property_for',
            field=models.CharField(choices=[('', 'Select Property For'), ('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=5),
        ),
        migrations.AlterField(
            model_name='buy',
            name='property_type',
            field=models.CharField(choices=[('', 'Select Property Type'), ('1BHK', '1 BHK'), ('2BHK', '2 BHK'), ('3BHK', '3 BHK'), ('4BHK', '4 BHK'), ('5BHK', '5 BHK'), ('6BHK', '6 BHK')], max_length=5),
        ),
        migrations.AlterField(
            model_name='buy',
            name='user_info',
            field=models.CharField(choices=[('', 'Select User'), ('Owner', 'Owner'), ('Agent', 'Agent')], max_length=5),
        ),
        migrations.AlterField(
            model_name='rent',
            name='city',
            field=models.CharField(choices=[('', 'Select City'), ('Dehli', 'Delhi'), ('Mumbai', 'Mumbai'), ('Kolkata', 'Kolkata'), ('Channai', 'Channai'), ('Noida', 'Noida'), ('Gurugram', 'Gurugram'), ('Dehradun', 'Dehradun'), ('Bangluru', 'Bangluru'), ('Pune', 'Pune')], max_length=5),
        ),
        migrations.AlterField(
            model_name='rent',
            name='parking',
            field=models.CharField(choices=[('', 'Select Parking'), ('Available, Closed', 'Available, Closed'), ('Available, Open', 'Available, Open'), ('Not Available', 'Not Available')], max_length=5),
        ),
        migrations.AlterField(
            model_name='rent',
            name='property_for',
            field=models.CharField(choices=[('', 'Select Property For'), ('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=5),
        ),
        migrations.AlterField(
            model_name='rent',
            name='property_type',
            field=models.CharField(choices=[('', 'Select Property Type'), ('1BHK', '1 BHK'), ('2BHK', '2 BHK'), ('3BHK', '3 BHK'), ('4BHK', '4 BHK'), ('5BHK', '5 BHK'), ('6BHK', '6 BHK')], max_length=5),
        ),
        migrations.AlterField(
            model_name='rent',
            name='user_info',
            field=models.CharField(choices=[('', 'Select User'), ('Owner', 'Owner'), ('Agent', 'Agent')], max_length=5),
        ),
    ]
