# Generated by Django 2.0 on 2018-03-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_portal', '0009_remove_rent_w_e_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='city',
            field=models.CharField(choices=[('', 'Select City'), ('Dehli', 'Delhi'), ('Mumbai', 'Mumbai'), ('Kolkata', 'Kolkata'), ('Channai', 'Channai'), ('Noida', 'Noida'), ('Gurugram', 'Gurugram'), ('Dehradun', 'Dehradun'), ('Bangluru', 'Bangluru'), ('Pune', 'Pune')], max_length=25),
        ),
        migrations.AlterField(
            model_name='buy',
            name='facing',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='furnished_state',
            field=models.CharField(choices=[('', 'Select Furnished state'), ('Not Furnished', 'Not Furnished'), ('Semi-Furnished', 'Semi-Furnished'), ('Full Furnished', 'Full Furnished')], max_length=50),
        ),
        migrations.AlterField(
            model_name='buy',
            name='parking',
            field=models.CharField(choices=[('', 'Select Parking'), ('Available, Closed', 'Available, Closed'), ('Available, Open', 'Available, Open'), ('Not Available', 'Not Available')], max_length=50),
        ),
        migrations.AlterField(
            model_name='buy',
            name='property_for',
            field=models.CharField(choices=[('', 'Select Property For'), ('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=50),
        ),
        migrations.AlterField(
            model_name='buy',
            name='property_type',
            field=models.CharField(choices=[('', 'Select Property Type'), ('1BHK', '1 BHK'), ('2BHK', '2 BHK'), ('3BHK', '3 BHK'), ('4BHK', '4 BHK'), ('5BHK', '5 BHK'), ('6BHK', '6 BHK')], max_length=10),
        ),
        migrations.AlterField(
            model_name='buy',
            name='user_info',
            field=models.CharField(choices=[('', 'Select User'), ('Owner', 'Owner'), ('Agent', 'Agent')], max_length=10),
        ),
        migrations.AlterField(
            model_name='rent',
            name='city',
            field=models.CharField(choices=[('', 'Select City'), ('Dehli', 'Delhi'), ('Mumbai', 'Mumbai'), ('Kolkata', 'Kolkata'), ('Channai', 'Channai'), ('Noida', 'Noida'), ('Gurugram', 'Gurugram'), ('Dehradun', 'Dehradun'), ('Bangluru', 'Bangluru'), ('Pune', 'Pune')], max_length=25),
        ),
        migrations.AlterField(
            model_name='rent',
            name='facing',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='furnished_state',
            field=models.CharField(choices=[('', 'Select Furnished state'), ('Not Furnished', 'Not Furnished'), ('Semi-Furnished', 'Semi-Furnished'), ('Full Furnished', 'Full Furnished')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rent',
            name='parking',
            field=models.CharField(choices=[('', 'Select Parking'), ('Available, Closed', 'Available, Closed'), ('Available, Open', 'Available, Open'), ('Not Available', 'Not Available')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rent',
            name='property_for',
            field=models.CharField(choices=[('', 'Select Property For'), ('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rent',
            name='property_type',
            field=models.CharField(choices=[('', 'Select Property Type'), ('1BHK', '1 BHK'), ('2BHK', '2 BHK'), ('3BHK', '3 BHK'), ('4BHK', '4 BHK'), ('5BHK', '5 BHK'), ('6BHK', '6 BHK')], max_length=10),
        ),
        migrations.AlterField(
            model_name='rent',
            name='user_info',
            field=models.CharField(choices=[('', 'Select User'), ('Owner', 'Owner'), ('Agent', 'Agent')], max_length=10),
        ),
    ]
