# Generated by Django 2.0 on 2018-03-20 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property_portal', '0010_auto_20180320_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=12)),
                ('contact', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
                ('usertype', models.BooleanField(choices=[('', 'Select User'), ('Owner', 'Owner'), ('Agent', 'Agent')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
